DROP DATABASE library;
CREATE DATABASE library;

USE library;
CREATE TABLE Book(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(30) unique,
    WRITER VARCHAR(30),
    PUBLISHER VARCHAR(30),
    PUBLISHED_YEAR INT
);
INSERT INTO BOOK(TITLE,WRITER,PUBLISHER,PUBLISHED_YEAR) VALUES ('My life','Vrinda','Vrinda',2019);
select * from book;