server:
  port: 8080
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
