server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metacube_parking
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/users/
      suffix: .jsp

      
home:
 notice : APP Property
 
welcome:
  message: Welcome to Parking System!! 